management:
  info.git.mode: full
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: cloud
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
---
spring:
  profiles: h2
  jpa:
    generate-ddl: true